# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

define "rent" A0
define "uno" B2:B4
define "dos" 125
let rent = 14
let B2 = 1
let B3 = 2
let B4 = 3
let A6 = 6
let B6 = @sum(uno)
let C6 = dos
