# This data file was generated by SCIM.
# You almost certainly shouldn't edit it.

let A0 = 12.8
label B0 = "12,34"
let C0 = 4.36
label A1 = "a"
label B1 = "b"
label C1 = "c"
label A2 = "d"
leftstring B2 = "izq"
label C2 = "centro"
label A3 = "'"
label B3 = ","
label C3 = "/"
label A4 = "\""
let B4 = 2
rightstring C4 = "derecha"
goto C0
