# This data file was generated by the Spreadsheet Calculator.  That is SC-IM, the improved one!
# You almost certainly shouldn't edit it.

set external_functions
let A0 = 2
let A1 = 1
let B1 = 2
let C1 = 6
let D1 = @getent(1,2)
goto D1
