# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
let A0 = 9-H0
let B0 = 4
let D0 = 9
let E0 = 8
let F0 = 7
let H0 = 8
let A1 = 2
let B1 = 5
let D1 = 6
let E1 = 5
let F1 = 4
let A2 = 3
let B2 = 6
label B4 = "algo"
goto B4
movetosheet "Sheet1"
