# This data file was generated by the Spreadsheet Calculator Improvised (SC-IM)
# You almost certainly shouldn't edit it.

format C 19 2 0
format 2 3
mark a C3
label A0 = "numero"
label B0 = "hora"
label C0 = "texto"
label D0 = "estado"
label E0 = "total"
let B1 = 6
rightstring D1 = "sigue"
let B2 = 7
label C2 = "algo bastante largo"
label D2 = "sigue"
let E2 = 23
let B3 = 8
let A4 = 1
let B4 = 9
goto C1
