# This data file was generated by the Spreadsheet Calculator Improvised (SC-IM)
# You almost certainly shouldn't edit it.

format 7 3
mark a B8
let A6 = 6
rightstring C6 = "sigue"
let A7 = 7
label B7 = "algo bastante largo"
label C7 = "sigue"
let D7 = 23
let A8 = 8
goto B8
