# This data file was generated by the Spreadsheet Calculator Improvised (SC-IM)
# You almost certainly shouldn't edit it.

set external_functions
newsheet "UNO"
let A0 = 1
newsheet "DOS"
let B1 = 2
newsheet "TRES"
let C2 = 4
goto C2
