# This data file was generated by SC-IM.
# You almost certainly shouldn't edit it.

set external_functions
label A0 = "Plumbing"
let B0 = 216
label A1 = "Heating"
let B1 = 144
label A2 = "Electric"
let B2 = 24
label A3 = "Upkeep"
let B3 = 13
goto A0
