# This data file was generated by the Spreadsheet Calculator.  That is SC-IM, the improved one!
# You almost certainly shouldn't edit it.

format A 20 3 0
format B 20 3 1
format C 20 3 2
mark a A1
mark b A1
mark c A1
mark d A1
mark e A1
mark f A1
mark g A1
mark h A1
mark i A1
mark j A1
mark k A1
mark l A1
mark m A1
mark n A1
mark o A1
mark p A1
mark q A1
mark r A1
mark s A1
mark t A1
mark u A1
mark v A1
mark w A1
mark x A1
mark y A1
mark z A1
rightstring A0 = "fixed-point"
rightstring B0 = "scientific"
rightstring C0 = "engineering"
let A1 = 12300
let B1 = 12300
let C1 = 12300
let A2 = 12300
let B2 = 12300
let C2 = 12300
let A3 = @sum(A1:A2)
let B3 = @sum(B1:B2)
let C3 = @sum(C1:C2)
goto D1
