# This data file was generated by the Spreadsheet Calculator Improvised (SC-IM)
# You almost certainly shouldn't edit it.

set external_functions
let A0 = 1
let B0 = A0+1
let A1 = A0+1
let B1 = A1+B0
let A2 = A1+1
let B2 = A2+B1
let A3 = A2+1
let B3 = A3+B2
let A4 = A3+1
let B4 = A4+B3
let A5 = A4+1
let B5 = A5+B4
let A6 = A5+1
let B6 = A6+B5
goto A1
