# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

set external_functions
newsheet "Sheet1"
movetosheet "Sheet1"
let A0 = 1
let B0 = 2
let C0 = 3
let D0 = 4
let E0 = 5
let F0 = 6
let G0 = 7
let H0 = 8
let I0 = 9
let J0 = 10
let K0 = 11
let L0 = 12
let M0 = 13
let N0 = 14
let O0 = 15
let P0 = 16
let Q0 = 17
let R0 = 18
let S0 = 29
let T0 = 30
let U0 = 31
let V0 = 32
let W0 = 33
let A1 = 2
let A2 = 3
let A3 = 4
let A4 = 5
let A5 = 6
let A6 = 7
let A7 = 8
let A8 = 9
let A9 = 10
let A10 = 11
let A11 = 12
let A12 = 13
let A13 = 14
let A14 = 15
let A15 = 16
let A16 = 17
let A17 = 18
let A18 = 19
let A19 = 20
let A20 = 21
let A21 = 22
let A22 = 23
let A23 = 24
let A24 = 25
let A25 = 26
let A26 = 27
let A27 = 28
let A28 = 29
let A29 = 30
let A30 = 31
let A31 = 32
let A32 = 33
let A33 = 34
let A34 = 35
let A35 = 36
let A36 = 37
let A37 = 38
let A38 = 39
let A39 = 40
let A40 = 41
let A41 = 42
let A42 = 43
let A43 = 44
let A44 = 45
goto A1
