# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
newsheet "dos"
movetosheet "dos"
let A0 = 1.14
let A1 = 1.16
let A2 = @sum(A0:A1)
let B3 = {"Sheet1"}!A2
goto B3
movetosheet "Sheet1"
let A0 = {"dos"}!B3+{"dos"}!A2
goto A2
