# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

set external_functions
newsheet "Sheet1"
movetosheet "Sheet1"
let A0 = 1
let B0 = A0+1
let C0 = 12
let A1 = A0+1
let B1 = A1+B0
let A2 = A1+1
let B2 = A2+B1
goto C1
