#SC THEME
color "type=HEADINGS fg=BLACK bg=WHITE bold=0"
color "type=HEADINGS_ODD fg=BLACK bg=WHITE bold=0"
color "type=CELL_SELECTION bg=BLACK fg=WHITE bold=0"
color "type=CELL_SELECTION_SC bg=WHITE fg=BLACK bold=0"
color "type=DEFAULT fg=WHITE bg=BLACK"
color "type=INPUT fg=WHITE bg=BLACK"
color "type=NORMAL fg=WHITE bg=BLACK"
color "type=WELCOME fg=WHITE bg=BLACK bold=0"
color "type=NUMB fg=WHITE bg=BLACK"
color "type=STRG fg=WHITE bg=BLACK bold=0"
color "type=DATEF fg=WHITE bg=BLACK"
color "type=EXPRESSION fg=WHITE bg=BLACK"
color "type=INFO_MSG fg=WHITE bg=BLACK"
color "type=ERROR_MSG fg=WHITE bg=BLACK"
color "type=MODE fg=WHITE bg=BLACK bold=0"
color "type=CELL_ID fg=WHITE bg=BLACK bold=1"
color "type=CELL_FORMAT fg=WHITE bg=BLACK bold=0"
color "type=CELL_CONTENT fg=WHITE bg=BLACK bold=1"
color "type=CELL_ERROR fg=WHITE bg=BLACK"
color "type=CELL_NEGATIVE bg=BLACK fg=WHITE"
