name: CI
run-name: continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        #os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
        os: [ubuntu-latest]
        #cc: [gcc, clang]
        cc: [gcc]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y valgrind bison
      - run: make -C src
        env:
          CC: ${{ matrix.cc }}
      - run: cd ./tests && ./run_all_tests.sh
        shell: bash
        env:
          CC: ${{ matrix.cc }}

